#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app" --action="stop"
ynh_systemctl --service="$app-celery" --action="stop" --log_path="/var/log/$app/$app-celery.log"
ynh_systemctl --service="$app-celery-beat" --action="stop" --log_path="/var/log/$app/$app-celery-beat.log"

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating NGINX web server configuration..."

ynh_config_change_url_nginx

#=================================================
# UPDATE OIDC REGISTRATION
#=================================================
ynh_script_progression "Updating authentication configuration..."

yamtrack_register_dex

#=================================================
# UPDATE CONFIGURATION
#=================================================
ynh_script_progression "Updating $app's configuration..."

yamtrack_setup_certs
yamtrack_setup_env

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start"
ynh_systemctl --service="$app-celery" --action="start" --log_path="/var/log/$app/$app-celery.log"
ynh_systemctl --service="$app-celery-beat" --action="start" --log_path="/var/log/$app/$app-celery-beat.log"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Change of URL completed for $app"
