#!/bin/bash

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# RESTORE REDIS DATABASE
#=================================================
ynh_script_progression "Loading additional settings..."

redis_db=$(ynh_redis_get_free_db)
ynh_app_setting_set --key=redis_db --value="$redis_db"

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression "Restoring the app main directory..."

ynh_restore "$install_dir"

#=================================================
# RESTORE THE DATA DIRECTORY
#=================================================
ynh_script_progression "Restoring the data directory..."

ynh_restore "$data_dir"

chown -R "$app:$app" "$data_dir"

#=================================================
# REINSTALL PYTHON DEPENDENCIES
#=================================================
ynh_script_progression "Reinstalling Python dependencies..."

pushd "$install_dir"
    ynh_safe_rm "$install_dir/venv"
    python3 -m venv venv
    chown -R "$app:" "$install_dir"
    ynh_hide_warnings ynh_exec_as_app "$install_dir/venv/bin/pip3" install --upgrade pip setuptools wheel
    ynh_hide_warnings ynh_exec_as_app "$install_dir/venv/bin/pip3" install -r "$install_dir/requirements.txt"
popd

#=================================================
# RE-REGISTER OIDC CLIENT IN DEX (IF AVAILABLE)
#=================================================
ynh_script_progression "Configuring authentication..."

yamtrack_register_dex

#=================================================
# RESTORE CONFIGURATION
#=================================================
ynh_script_progression "Restoring $app's configuration..."

yamtrack_setup_env

#=================================================
# RESTORE THE NGINX CONFIGURATION
#=================================================
ynh_script_progression "Restoring the NGINX configuration..."

ynh_restore "/etc/nginx/conf.d/$domain.d/$app.conf"

#=================================================
# RESTORE THE POSTGRESQL DATABASE
#=================================================
ynh_script_progression "Restoring the PostgreSQL database..."

ynh_psql_db_shell < ./db.sql

#=================================================
# RESTORE SYSTEMD
#=================================================
ynh_script_progression "Restoring systemd configurations..."

ynh_restore "/etc/systemd/system/$app.service"
ynh_restore "/etc/systemd/system/$app-celery.service"
ynh_restore "/etc/systemd/system/$app-celery-beat.service"
systemctl enable "$app.service" --quiet
systemctl enable "$app-celery.service" --quiet
systemctl enable "$app-celery-beat.service" --quiet

#=================================================
# RESTORE THE LOGROTATE CONFIGURATION
#=================================================
ynh_script_progression "Restoring the logrotate configuration..."

mkdir -p "/var/log/$app"
chown -R "$app:$app" "/var/log/$app"

ynh_restore "/etc/logrotate.d/$app"

#=================================================
# INTEGRATE SERVICE IN YUNOHOST
#=================================================
ynh_script_progression "Integrating service in YunoHost..."

yunohost service add "$app" --description="Yamtrack web server" --log="/var/log/$app/$app.log"
yunohost service add "$app-celery" --description="Yamtrack Celery worker" --log="/var/log/$app/$app-celery.log"
yunohost service add "$app-celery-beat" --description="Yamtrack Celery beat" --log="/var/log/$app/$app-celery-beat.log"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start"
ynh_systemctl --service="$app-celery" --action="start" --log_path="/var/log/$app/$app-celery.log"
ynh_systemctl --service="$app-celery-beat" --action="start" --log_path="/var/log/$app/$app-celery-beat.log"

#=================================================
# RELOAD NGINX
#=================================================
ynh_script_progression "Reloading NGINX..."

ynh_systemctl --service=nginx --action=reload

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"
